site_name: MSCore  Docs
site_author: HexChap
site_description: >-
  Toolkit for writing HTTP microservices using FastAPI, Pydantic and TortoiseORM

nav:
  - Home: index.md
  - Tutorial:
      - tutorials/index.md
      - Easier FastAPI and Tortoise setup: tutorials/setup_app.md
  - Contributing: contributing.md
  - Reference:
      - reference/index.md
      - ms_core.setup: reference/setup.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

color_mode: light
user_color_mode_toggle: true
theme: 
  name: material
  features:
    - content.code.annotate
    - content.code.copy
    - navigation.indexes
    - navigation.instant

  repo_name: HexChap/MSCore
  repo_url: https://github.com/HexChap/MSCore

  icon:
    repo: fontawesome/brands/git-alt

plugins:
- search
- mkdocstrings